### ISSUE TITLE
Last resort only counting PP?

### ISSUE THREAD

**Issue by segabl** [DizzyEggg/pokeemerald#238]
It seems last resort only counts the number of used PP instead of checking if every move was used. I spammed last resort in a test battle cause I was testing something else and it suddenly worked after a few tries.

**Comment by DizzyEggg** [comment]
Hopefully fixed, the issue was instead of checking if the other known moves were used(1, 2 or 3 other moves depending on how many were known), it also counted using Last Resort.
So, if mon had 3 moves, for example, Last Resort, Mud Sport and Water Sport and Mud Sport was used, and then Last Resort, it would fail. But if Last Resort was used again after that, it would work, because it counted using Last Resort as using Water Sport. 

bcf6b02a5
