### ISSUE TITLE
Life orb freezes the game if it faints its holder

### ISSUE THREAD

**Issue by Ryuhouji** [DizzyEggg/pokeemerald#283]
If your mon is holding a Life Orb, and it deals enough damage to faint your mon, the game softlocks.

**Comment by LOuroboros** [comment]
Can't confirm. I made a branch merging in the item_expansion along with the battle_engine_v2 and the Life Orb isn't freezing the game if it kills its holder on my end. Neither on single battles nor double battles.
https://streamable.com/wvq1l
https://streamable.com/0voys

I did notice an issue in Double Battles because of this test, but this isn't the right place to bring it up I think.

**Comment by DizzyEggg** [comment]
What's the issue @LOuroboros ?

**Comment by LOuroboros** [comment]
> What's the issue @LOuroboros ?

I already told you about it on Discord @DizzyEggg, but I guess I should mention it here too, for the record.

> My Torchic with Life Orb killed an opponent Poochyena in a double battle, it died afterward because of the Life Orb, and the exp. obtained from killing that Poochyena wasn't distributed until their ally used a move.
https://streamable.com/0voys
I don't recall how double battles work specially in the newer games, but shouldn't the exp. be distributed right after the kill?

**Comment by DizzyEggg** [comment]
Couldn't be reproduced
