### ISSUE TITLE
The animation of Diamond Storm freezes the game

### ISSUE THREAD

**Issue by Toby313** [DizzyEggg/pokeemerald#410]
![pokeemerald_1592231203203](https://user-images.githubusercontent.com/56541253/84669493-366d3980-af25-11ea-859e-36fe6603d945.png)
A purple particle seems to get stuck while the rest keeps moving.

**Comment by LOuroboros** [comment]
I gave it a test, and the problem seems to be caused by one of the following lines, seeing how when uncommented, the animation can work from beginning to end without freezing the game.
![notepad++-2020-06-15_18-45-52](https://user-images.githubusercontent.com/4485172/84709450-8a354e00-af38-11ea-9d9d-5fdca6435ef6.png)

Hopefully, that'll make things easier to whoever decides to fix it.
