### ISSUE TITLE
Need documentation - types table - suggestion

### ISSUE THREAD

**Issue by jmwielandt** [DizzyEggg/pokeemerald#80]
Hi, 
¿where is the table of resistainces and etc. of types?
On pret's repo is on `src/battle_main.c`, around line 343.

Now, suggestion.
Maybe you could manage all systems by it's own on different branches and then have other one to merge all.

**Comment by DizzyEggg** [comment]
I'll come up with some documentation later. The type table is called sTypeEffectivenessTable and can be found in src/battle_util.c at line 232.

As for you suggestion, I can imagine that not everyone wants all the feature my repo has to offer, but it would be extremely hard to keep some features out and some in, because of how everything is interleaved in the battle system.
